variables:
  GIT_URL: gitlab.com
  GIT_REPO: wpify/custom-fields
  GIT_NAME: Daniel Mejta
  GIT_EMAIL: daniel@mejta.net
  CLONE_PATH: /root/custom-fields

include:
  - project: 'wpify/gitlab-ci-templates'
    ref: master
    file:
      - 'jobs/nvm.yml'

assets:
  stage: .pre
  extends: .nvm
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build
    expire_in: 1 week
  when: manual

.git:
  image: alpine:latest
  variables:
    GIT_SSH_COMMAND: /usr/bin/ssh -i ~/.ssh/id_rsa
  before_script:
    - apk update
    - apk add openssh-client bash git rsync
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY" >> ~/.ssh/id_rsa
    - echo "$PUBLIC_KEY"  >> ~/.ssh/id_rsa.pub
    - ssh-keyscan -t rsa "${GIT_URL}" >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/id_rsa.pub
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "${GIT_EMAIL}"
    - git config --global user.name "${GIT_NAME}"
    - git clone "git@$GIT_URL/$GIT_REPO.git" "$CLONE_PATH"

deploy_master:
  stage: deploy
  extends: .git
  script: |
    # extract latest message
    message=$(git log -1 --pretty=%B)

    # remove /build/ from .gitignore file
    sed -i '/\/build\//d' ./.gitignore

    # copy changes to deploy path
    rsync -a --delete --exclude '.git' $CI_PROJECT_DIR/ $CLONE_PATH/

    # Get current status
    git status --porcelain

    # If anything changed, commit that to the origin
    if ! git diff-index --quiet HEAD --; then
      echo "adding"
      git add .
      echo "commiting"
      git commit -m "$message"
      echo "pushing"
      echo "git push --force origin:$CI_COMMIT_REF_NAME"
      git push --force origin:$CI_COMMIT_REF_NAME
    fi
  only:
    - master

deploy_tag:
  stage: deploy
  extends: .git
  script: |
    # get the tag
    tag=$(git describe --tags)

    # go to target repository
    cd $CLONE_PATH

    # create and push the tag
    git tag "$tag"
    git push --tags
  only:
    - tags
